version: "3.9"

services:

  web-client:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: node_base
    volumes: 
      - ../web-client:/code/web-client
      - /code/web-client/node_modules
    working_dir: /code/web-client
    entrypoint: ["npm", "run", "dev"]
    env_file: ../.env

  web-api:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_base
    volumes: 
      - ../web-api:/code/web-api
      - /code/web-api/target
      - ../rpc/:/code/rpc/
    working_dir: /code/web-api
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      ACCOUNT_SERVICE_URI: http://account
      DICTIONARY_SERVICE_URI: http://dictionary

  account:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_ms
    volumes: 
      - ../services/account:/code/services/account 
      - /code/services/account/target
      - ../rpc/:/code/rpc/
    working_dir: /code/services/account
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      DB_CONNECTION_URI: mongodb://root:root@db:27017
      JWT_SECRET: some-secret

  dictionary:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_ms
    volumes: 
      - ../services/dictionary:/code/services/dictionary
      - /code/services/dictionary/target
      - ../rpc/:/code/rpc/
    working_dir: /code/services/dictionary
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      DB_CONNECTION_URI: mongodb://root:root@db:27017
      VOCABULARY_URL: https://www.vocabulary.com/dictionary

