version: "3.9"

services:

  web-client:
    image: word-nerd/web-client
    container_name: word-nerd-web-client
    ports:
      - "${WEB_CLIENT_PORT}:80"
    depends_on:
      - web-api
    healthcheck:
      test: "curl -f http://localhost:80 || exit 1"
      start_period: 15s
  
  web-api:
    image: word-nerd/web-api
    container_name: word-nerd-web-api
    ports:
      - "${WEB_API_PORT}:80"
    depends_on:
      - account
      - dictionary
    healthcheck:
      test: "curl -f http://localhost:80/health || exit 1"
      start_period: 15s

  account:
    image: word-nerd/account
    container_name: word-nerd-account
    ports:
      - "${ACCOUNT_MS_PORT}:80"
    depends_on:
      - db
    healthcheck:
      test: "grpc_health_probe --addr=http://0.0.0.0:80 --service=account.Account"
      start_period: 15s

  dictionary:
    image: word-nerd/dictionary
    container_name: word-nerd-dictionary
    ports:
      - "${DICTIONARY_MS_PORT}:80"
    depends_on:
      - db
    healthcheck:
      test: "grpc_health_probe --addr=http://0.0.0.0:80 --service=dictionary.Dictionary"
      start_period: 15s

  search:
    image: word-nerd/search
    container_name: word-nerd-search
    ports:
      - "80"
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v1.2
    container_name: meilisearch
    ports:
      - "7700:7700"

  db:
    image: mongo
    container_name: word-nerd-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT}:27017"

  db-express:
    image: mongo-express
    container_name: word-nerd-db-express
    ports:
      - "${DB_EXPRESS_PORT}:8081"
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/

    
