version: "3.9"

services:

  web-client:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: node_base
    volumes: 
      - ../web-client:/code/web-client
      - client-v:/code/web-client/node_modules
    working_dir: /code/web-client
    entrypoint: ["npm", "run", "dev"]
    env_file: ../.env

  web-api:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_base
    volumes: 
      - ../web-api:/code/web-api
      - api-v:/code/web-api/target
      - ../rpc/:/code/rpc/
      - ../common-rs/:/code/common-rs/
    working_dir: /code/web-api
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      ACCOUNT_SERVICE_URI: http://account
      DICTIONARY_SERVICE_URI: http://dictionary

  account:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_ms
    volumes: 
      - ../services/account:/code/services/account 
      - account-v:/code/services/account/target
      - ../rpc/:/code/rpc/
      - ../common-rs/:/code/common-rs/
    working_dir: /code/services/account
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      DB_CONNECTION_URI: mongodb://root:root@db:27017
      JWT_SECRET: some-secret

  dictionary:
    build: 
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_ms
    volumes: 
      - ../services/dictionary:/code/services/dictionary
      - dict-v:/code/services/dictionary/target
      - ../rpc/:/code/rpc/
      - ../common-rs/:/code/common-rs/
    working_dir: /code/services/dictionary
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      DB_CONNECTION_URI: mongodb://root:root@db:27017
      VOCABULARY_URL: https://www.vocabulary.com/dictionary

  search:
    build:
      context: .
      dockerfile: ./local.Dockerfile
      target: rust_ms
    volumes:
      - ../services/search:/code/services/search
      - search-v:/code/services/search/target
      - ../common-rs/:/code/common-rs/
    working_dir: /code/services/search
    entrypoint: ["cargo", "watch", "-x", "'run'"]
    environment:
      RUST_BACKTRACE: 1
      MEILISEARCH_CONNECTION_URI: http://meilisearch:7700
      MEILI_MASTER_KEY: 'mySuperSecretKey'

  meilisearch:
    environment:
      MEILI_MASTER_KEY: 'mySuperSecretKey'

volumes:
  search-v:
  dict-v:
  account-v:
  api-v:
  client-v:
